### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/mechanicalshakerexperiments#12]
### 2022

- Frequency spectra
- Time series (cross correlation)
- Time keeping
- Facilitate visual exploration (see #10)

### Backlog

- Compare acceleration metrics
- Door experiments => check that data is well loaded
- Update contributors

**Comment by Anne-Linde** [comment]
- [x] Build in check for selecting the axis that measured the shaking signal (i.e., the axis aligned with the shaking direction)

**Comment by Anne-Linde** [comment]
During frequency analysis I encountered the following:

- As sampling frequency of activPAL could not be set higher than 20 Hz. in both high and low freq. the activPAL data is considered. Therefore, I removed the activPAL from the ms_hfcr experiment (L156-159) for now
- How to deal with outliers? 
- Normality check needs to be performed on the residuals of the observations, not the observations itself
- I analysed for the HA, but do we also/only want to consider the normalized HA in the frequency analysis? --> as for the normalized HA we don't depend on amplitude?

**Comment by Anne-Linde** [comment]
Data was subsetted to include the mixed frequency experiment.. do we want to still include this?
https://github.com/wadpac/mechanicalshakerexperiments/blob/frequency-spectrum/inst/researchcode/subset_data_HA.R

**Comment by Anne-Linde** [comment]
Preliminary results of frequency spectra and time series.
Still to do:
- [x] Check if the correct normalisation for the HA is used (see Line 52 in subset_data_ms_flat_HA.R)
- [x] Construct VM
- [x]  Subset data to include VM in the subset
- [x]  Calculate cross-correlations for VM
- [x] Heatmaps for all devices (HA and VM)
- [x] Discuss how to improve the boxplots (for the frequency spectra)
- [ ] Within brands analyses for spectra
- [x] Statistical comparison cross-correlations for the HA between and within brands --> descriptive analyses suffice

**Comment by Anne-Linde** [comment]
Focus the results at comparing the horizontal axis (HA) between brands, by taking the following steps:

- [x] Reload the data (including the resampling for the devices, and the new data labels)
- [x] Subset the data for the mechanical shaker machine experiments, and select the HA only
- [x] Rerun frequency spectrum analyses and clean code
- [x] Rerun cross-correlation analyses and clean code
- [x] Adjust cross-correlation plots (include new labels, and devices with the same sampling frequency only)
