### ISSUE TITLE
Synchronise input

### ISSUE THREAD

**Issue by Anne-Linde** [wadpac/mechanicalshakerexperiments#35]
After checking the pairwise plots for low correlations, we found that the input signals are not yet correct. In order to get the correct input for the cross-correlations

- [x] create data synchronising script
- [x] build-in check: start and end time are equal for the signals that will be compared
- [x] remove data where shaking frequency was null, or high sampling frequency was performed double for some devices
- [x] load in the same data for frequency spectrum analyses and cross-correlations
- [x] rerun the analyses

**Comment by Anne-Linde** [comment]
Started in the branch: issue35_synchronize_input

**Comment by vincentvanhees** [comment]
Maybe then also make sure that frequency spectrum analysis uses the exact same time series. In that way we know that data has been cleaned and process identically.

**Comment by Anne-Linde** [comment]
Data also still contains -1 shaking_frequency values, I think we need to remove these too

**Comment by Anne-Linde** [comment]
> Maybe then also make sure that frequency spectrum analysis uses the exact same time series. In that way we know that data has been cleaned and process identically.

For the frequency domain, signals are not required to have the same length for "pairwise" calculation, so maybe only perform the removal of the null condition and -1 (where the experiment was stopped), and remove repeated measures due to device(s) that got loose during the experiment.

**Comment by vincentvanhees** [comment]
To make a strandardised comparison it helps to know that we are using the exact same time segments. If we accidentally include or remove parts of the experiments in one sensor brand then that would invalidate the comparison of the frequency spectra. The movement exposure needs to be identical.

**Comment by Anne-Linde** [comment]
Things to check

Do we include activPAL in the frequency spectrum analyses for the high sampling frequency experiment? --> we first included this, but after the feedback by @vincentvanhees I'm in doubt
After discussion:

- [x] Exclude activPAL from all analyses during the high sampling frequency experiment

**Comment by Anne-Linde** [comment]
- [x] Check the sampling frequency of Ax_834 

This is 25 Hz for the low sampling frequency experiment, and 100 Hz for the high sampling frequency experiment. This is as expected, so include the signal

**Comment by Anne-Linde** [comment]
activPAL data was removed from high sampling frequency experiment by adjusting the inspect_clean_data.Rmd L36 to L43
