### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/mechanicalshakerexperiments#4]
Listing possible next steps:

**Comment by vincentvanhees** [comment]
## Data (pre)-processing

### Loading and storing of raw data (Annelinde)
- [x] Add to pre-processing for ActiGraph the filling up off sleep.mode time segments. When timestamps jump by more than a second fill with last acceleration value. -> this is already implemented in metric_analyses.R
- [x] Expand with MOX ~~and Shimmer~~
~~- [ ] Shimmer getspecs; which settings were used?~~
- [x] Activpal not converted to g-units yet
- [x] Acttrust: selected variables (normalized per second) Activity value calculated in Proportional Integral Mode, Activity value calculated in Time Above Threshold mode, and Activity value calculated in Zero Crossing Mode
- [ ] Specifications: what is the dynamic range of Acttrust, MOX?

### Update terminology and repo structure (Vincent + Annelinde)

Protocol | Session | Description | New name
--- | --- | ---  | --- 
1 | 1 | In box for whole day | timer_check
2 | 1 | Shaker machine - high freq | ms_hfcr
2 | 2 | Shaker machine - low freq | ms_lfcr
2 | 3 | Shaker machine -  mixed freq | ms_mfcr
3 | 1 | Shaker machine -  high freq + mixed dyn range | ms_hfmr
3 | 2 | Shaker machine -  low freq + mixed dyn range | ms_lfmr
3 | 3 | Shaker machine -  all in bag | ms_bag
3 | 4 | On door | door



- [x] Propose new naming for protocol and session numbers
- [x] Implement new naming
- [x] Add man folder
- [x] Add DESCRIPTION
- [x] Add namespace
- [x] Write documentation with Roxygen2

**Comment by vincentvanhees** [comment]
Leaving some notes based on work done today:

- Metric exploration now taking shape.
- Activpal data when incorporated in metric exploration shows strange pattern, with low accelerations at the transition point, which would hint at a bug in my code. => to be investigated
- Anova currently shows differences for all metrics across brands, even when I leave out Activpal. => Will need to work on better visualisations to visualise this, e.g. boxplot per conditions per brand.
- More insight gained in why MIMSlight differs from MIMSunit, it is primarily the aggregation step.
- Will need to expand metrics with all the other metrics from GGIR, e.g. BFEN, HFENplus. ENMOa

**Comment by vincentvanhees** [comment]
Notes based on the work I did today in the `explore_vincent` development branch:

My quick attempt to calibrate the signals is not very convincing, but potentially critical for our analysis. I have now implemented new code that uses protocol 2 session 4 to perform the auto-calibration procedure.

To make this work I had to change the `data_description_V4.xlsx` file as follows:
- Protocol 2 session 4 becomes protocol 2 session 3, and shakerfrequency is now zero, because we do not want getwindow to ignore these data. Another option is to make it negative, to ease filtering it out when we focus on shaker experiment data. 
-Next, I had to reprocess protocol 2 session 3 data such that the non-movement segments are part of the output.
- I wrote `derive_calibration_coefficients.R` which allows me to load these files and apply the auto-calibration algorihtm, and then store the resulting coefficients to an output file.

**Still to do:**
- Use those correction coefficients in further analysis.
- Tidy up file paths and analyses output structure. I have been creating folders and result files among the data files. It may be better to move all this to a separate _analyses_ directory.
- Change 0 Herz shaker frequency to -2 for box experiment

**Comment by vincentvanhees** [comment]
**Notes on progress today (17-9-2021):**

- After our discussion about the folder names I revised them again because I feel the names did not capture the essence yet. Both raw data files produced by the sensors and our processed data represent the raw acceleration signal, in the sense that neither is filtered or aggregated. Therefore, I think a better way to refer to them is as "structured_raw_data" and "unstructured_raw_data".
- Metric comparison code looks ready, I am now running it. This should generate visual comparisons and applies Anova and Tukey test to aid quick comparison.
- Where I wrote "Change 0 Herz shaker frequency to -1 for box experiment" above, I have no changed this to -2, because then it will not be excluded by loadlog function.
- Expanded metric comparisons with metrics BFEN, HFENplus, HFEN, and Sadeh counts.

**To do for next time:**
- Go through all steps of the process
- Discuss and where needed improve plots and statistical analysis

**Comment by vincentvanhees** [comment]
Relevant articles for metrics:

blog post: https://medium.com/@vincentvanhees/ten-misunderstandings-surrounding-information-extraction-from-wearable-accelerometer-data-a4f767a865b6
Henri Vähä-Ypyä, MAD: https://onlinelibrary.wiley.com/doi/10.1111/cpf.12127
van Hees, various metrics: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0061691
Bai, Activity Index: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0160644
Karas review paper: https://link.springer.com/article/10.1007%2Fs12561-018-9227-2
MIMSunit: https://cran.r-project.org/web/packages/MIMSunit/index.html
schudmachine study 2019: https://pubmed.ncbi.nlm.nih.gov/19276852/

**Comment by vincentvanhees** [comment]
I see "Specifications: what is the dynamic range of Acttrust, MOX?" is not ticked yet, is this still a open?
If not, then I think we can close this issue.

**Comment by Anne-Linde** [comment]
> This is still open (see lines 41 and 64 of getspecs function)
