### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/mechanicalshakerexperiments#9]
Idea is to have:
- Unstructured data (raw data)
- Structured data
- Derived data, e.g. frequency spectra
- Description file

- [x] Zip file with raw folder structure
- [x] Zip file with derived data structure
- [x] Labels file
- [x] Brief documentation with reference to this repository
- [x] Upload video, without comments

**Comment by Anne-Linde** [comment]
- [x] Adjust the script subset_data_ms_flat_HA.R to structure data for current paper (only including ms_hrcr and ms_lfcr)

**Comment by Anne-Linde** [comment]
Data is documented en publised here: https://zenodo.org/record/8160791
